---
bibliography: library.bib
csl: marine-ecology-progress-series.csl
header-includes: 
- \usepackage{setspace}
- \doublespacing
output:
  pdf_document:
    fig_caption: yes
indent: true
---

# Discussion 


To date, no studies have incorporated the affects of other filter-feeders and complex environmental conditions on Olympia oyster filtration functions.
My results indicate that the habitat clearance rate (HCR) between *C. gigas* aquaculture and restored *O. lurida* habitat are similar when measured in the field; inherently including all bivalve filtration contributions and their responses to dynamic field conditions.
The field measurements I present also show HCRs are highly variable at each site.
These findings suggest that the clearance rate differences between *O. lurida* and *C. gigas* are less important when  we consider *O. lurida* as a foundation species that realistically filters alongside other bivalves in dynamic environmental conditions. 

Olympia oysters are smaller and less robust filter-feeders than the Pacific oyster, according to previous single-species studies conducted in controlled environments [@Gray2018; @ZuErmgassen2013c].
This physiological difference has called into question to filtration functions that restored Olympia oyster habitat can provide to Pacific coast bays and estuaries [@ZuErmgassen2013c].
@Gray2018 found that maximum clearance rates of *C. gigas* are almost twice that of *O. lurida* under laboratory conditions. 
In addition, their Yaquina Bay, OR in situ trials recorded *O. lurida* averaging 0.78 L h^-1^g^-1^ in the dry season and 0.19 L h^-1^g^-1^ in the wet season, whereas *C. gigas* averaged 0.95 L h^-1^g^-1^ in the dry season and 1.06 L h^-1^g^-1^ in the wet season.
A direct comparison between these results and my measured HCRs is not possible because I only have direct biomass measurements for one site, Deanza, and biomass estimates for one site, San Rafael.
To date, estimates of restored *O. lurida* habitat filtration functions are made with single-species models [@ZuErmgassen2016; @Gray2019a; @ZuErmgassen2013c]. 
The single-species HCR estimate at Deanza is 1.13 L hr^-1^m^-2^ according to @Gray2018's all-season in situ *O. lurida* clearance rate model when Deanza average OC and temperature are used, and *O. luida* biomass converts the model' output's metric (L hr^-1^g^-1^) to HCR (L hr^-1^m^-2^).
Deanza's average HCR measured in this study is 105 L hr^-1^m^-2^, two orders of magnitude different than the single-species estimate made by @Gray2018's all-season model. 
My HCRs have a greater range of values than @Milbrandt2015 that conducted whole-habitat in situ measurements on restored bivalve beds in Florida and reported a range from -26 to 157 L hr^-1^m^-2^.
***Use rough biomass estimate for Morro Bay to compare to Wheat & Ruesink 2013 l/hr/g***
Cranford et al. 2011 has list of studies for gigas

This comparison brings up several points about estimating *O. lurida* filtration functions, 1) the Yaquina Bay model may not incorporate conditions found in California bays, making the model inappropriate to estimate *O. lurida* filtration with different water quality; 2) *O. lurida* lives among other filter-feeders that can contribute substantially to filtration; 3) The Yaquina Bay model was conducted in a flow-through chamber and the oysters were not in a natural hydrodynamic environment, which may affect bivalve feeding behavior.

Biomass is an important metric that is proportional to shell length which is in turn proportional to gill size and thus bivalve pumping rate [@Cranford2011].
However, biomass is time consuming to measure directly and requires bivalve collection, sacrifice, cleaning, separation from the shell, oven drying, and weighing. 
Many restoration practitioners may not wish to sacrifice bivalves from a restored habitat or have the resources to process the samples to better estimate filtration functions of the habitat. 
Future studies will benefit from a suite of models that predict bivalve species-specific biomass from shell length measurements, allowing monitoring efforts to measure bivalve shell length without disturbing the habitat to estimate habitat biomass.
In this paper, I presented a highly predictive (ln(DTWg) = -11.1 + 2.47ln(ShellLength), R^2^ = 0.73, *p* = < 0.0001) allometric model to estimate *O. lurida* biomass from shell length based on data from Newport Bay, CA that can be used in future southern California studies.
Allometric relationships may vary regionally, and more studies relating shell length to biomass are needed that incorporate *O. lurida* in other locations. 

My in situ method inherently included natural hydrodynamic conditions formed from the interaction between oyster habitat physical characteristics and water flow dynamics that dictate food availability and quality to filter-feeders.
@Sanford1997 explains that hydrodynamics interact with aquatic ecosystems from large bay-wide scales to small-scale plankton interactions, and are not easy to simulate.
Bivalves living in restored *O. lurida* habitat create a rough surface that produces drag and breaks up the the water flow momentum [@Dame2012; @VanDuren2006].
This basic interaction dissipates upward creating a velocity gradient from the bottom (lower velocity) into the water column (higher velocity) known as the boundary layer [@Dame2012].
The boundary layer is important to bivalve filter-feeders because this is where they access water column seston for feeding [@Muschenheim1987], and why I positioned my instruments at approximately the height of the oyster habitat [@Grizzle2008].
The height of the boundary layer can be affected by the arrangement of bivalves and flow speed [@Lim2020], and mostly consists of turbulent flow in natural rough environments like bivalve beds [@Dame2012; @Styles2015].
Turbulent flow within the boundary layer increases interaction and mixing with the larger water current, thus particle flux [@Muschenheim1987], and is generally characteristic of natural water bodies even in extremely low velocity scenarios [@Sanford1997].
Field conditions like depth and water flow velocity constrained my field days and deployment duration, resulting in filtration function snapshots.
Shallow water depth relative to the amount of bivalves ensures that bivalves have a greater influence on water column properties [@Wheat2013] and high water velocities can suspender sediments into the water column [@Dame1985; @Widdows1998; @Harsh1999].

Although my measurements do not represent a comprehensive look at filtration function across tidal and hydrodynamic conditions, they do represent filtration function at similar tidal and hydrodynamic conditions at each site (e.g. Tide, Depth, Velocity in Table 1).
Water depth and hydrodynamics may partial explain the similar HCRs between Morro Bay *C. gigas* aquaculture and restored *O. lurida* habitat.
Morro Bay consisted of floating grow bag lines that rose from the sediment surface with increasing water depth.
This floating action may have disturbed bottom sediments, clouding measurements, and created a 'moving target' for the water quality instruments.
Water quality instruments were positioned at the height of the bivalves, but at Morro Bay this height gradually increased with the flood tide, and may have partly missed the filtration signal creating a lower HCR than expected for *C. gigas* aquaculture.
Floating or off bottom *C. gigas* aquaculture may not provide the same biochemical filtration function as *O. lurida* beds as waste products are not always deposited on the sediment surface and made available to other benthic organisms; although this filtration function is not directly quantified through HCRs.
In addition, Morro Bay and San Rafael were not continuous habitat like Deanza and Shellmaker, and had intermixed portions of mudflat and bivalve habitat.
This patchy habitat may have caused complex hydrodynamics like eddies, where water particles are retained longer than the average water flow, physically removing Chl $\alpha$ from the main water flow measured by the downstream instrument.
Chl $\alpha$ retention in eddies could be conflated as bivalve filtration.
This is especially possible at San Rafael where the *O. lurida* habitat consisted of an array of 2m x 2m shell bag reefs each with a 1m relief above the sediment. 
Considering the extremely low *O. lurida* biomass at San Rafael compared to Deanza, one would not expect San Rafael to have a similar range of HCRs. 
This similarity may be an artifact of San Rafael's patchy and high relief habitat that creates sediment seston sinks on the leeward side of the shell bag reef structures.

Given the similar tidal and hydrodynamic conditions within each site, my results still show highly variable HCRs within each site (Figure 3).
High variability in field filtration measurements is well documented even along short periods of time (@Grizzle2008; reviewed by @Cranford2011).
Bivalves feeding on natural seston are shown to have high variation in clearance rates over short and long periods of time [reviewed by @Cranford2011].
In addition, this variation in HCRs could be the result of measuring hundreds and even thousands of bivalves. 
Individual feed behavior can be highly variable in short time periods [@Newell2005], and even under favorable conditions, a substantial portion of individual bivalves may not actively feed or feed at a reduced capacity [@Dolmer2000; @Saurel2007]

Describe negative numbers

Most filtration studies measure individual bivalves or small groups of individuals, where it is common to exclude individuals not filtering (i.e. close valves) [. 
This method artificially inflates feeding behavior by excluding the non-filtering individuals, and may over-estimate filtration functions when scaled to a habitat scale [@Harsh1999]. 


Simply expanding individual filtration rates to other areas need to account for water depth, as bivalves may not have the same access to food at depth or the whole water column [@Monismith1990; @Wheat2013]

Habitat Clearance Rates differ from individual bivalve clearance rates, as they inherently include variables that complicate individual filtration models. 

By measuring the whole habitat, we are incorporating and averaging individual bivalve's feeding responses to environmental conditions, and resolve the issue of expanding individual filtration rates to habitat levels (see Cranford et al. 2011).

Fast moving water or wind driven waves can re-suspend benthic sediments into the water column [@Widdows1998] leading to a net export of chl $\alpha$ from oyster habitats and negative HCRs.








## Extra Text
"Chlorophyll declined 9.6% per half hour in water passing on-bottom adult oysters and 41% for long-line adult oysters, whereas chlorophyll concentrations increased as water flowed across tide flats without adult oysters" [@Wheat2013]

Different species have different ideal water velocities for feeding [@Cranford2011].
Slow velocity, although possibly ideal for individual filtration [@Grizzle1992], can lead to food depletion for downstream animals (Monismith et al 1990 in Harsh & Luckenbach1999). 
On the other hand, both higher flows and shallow estuaries can redistribute particles throughout the water column replenishing food for bivalve filter feeders (Officer 1982 & Fredett 1989 in Harsh & Lauckenbach1999) (Holligan et al. 1984 cited in @Judge1993)
In addition, deeper water might limit benthic bivalves access to food (citations in Ruesink et al. 2005), while the orientation of oysters relative to the waterfowl may effect feeding behavior[@Grizzle1992; @Harsh1999].



@Harsh1999's flume study using varying flow speeds and *C. virginica* found that filtration rates were generally similar at less than 6cm/s, and "more negative rates > 6cm/s.

Slow flow can lead to food depletion to downstream animals (Monismith et al 1990 in Harsh & Luckenbach1999).

Vertical mixing can redistribute particles throughout the water column replenishing food for bivalve filter feeders (Officer 1982 & Fredett 1989 in Harsh & Lauckenbach1999)

Water dynamics in shallow estuaries often mixes water column "eliminating stratification of chlorophyll (Holligan et al. 1984 cited in @Judge1993).

Deeper waters might limit the access that benthic bivalves have to food (citations in @Ruesink2005).

Moreover, various filter-feeding taxa preferentially select for specific particle sizes [@Gedan2014; @Gray2016] depending on feeding physiology [@Elsey1935], leading to possible resource partitioning or competition that effects the net filtration [@Byers2014].

This suggests that filtration rates among *O. lurida* habitats, may have unique filtration rates locally or regionally depending on the composition of filter-feeders, and laboratory methods a likely insufficient at estimating habitat-level filtration functions. 

Gray & Langdon (2017) point out that O. lurida selects larger particles from the water column compared to C. gigas, likely because of anatomical differences in gill ostea, which may differentiate the quality of filtration by each species. 

C. gigas is also faster growing, larger, and has a greater filtration rate than O. lurida (zu Ermgassen, Gray, et al. 2013, Gray & Langdon 2017)





### Restate Research Goals
   
The goal of this paper was to characterize the insitu filtration functions of several types of constructed oyster habitat in California that incorporate whole-habitat and environmental effects. 
More precise methods of measuring bivalve filtration exist (e.g. flume studies @Harsh1999, bio-deposition, particle clearance), but they compromise the ability to incorporate the dynamic environmental and biological conditions that exist in actual oyster habitats (citations?). 

### Assumptions / Condition Description

Our in situ methods, while inherently incorporating the affects of environmental and biological conditions, have several assumptions important in contextualizing our findings. 
First, we assumed that water flowed linearly from the upstream instrument to the downstream instrument, thus both instruments measured the same uninterrupted mass of water. 
We observed and characterized the water dynamics at each site using Rhodamine WT before taking any data.
Rhodamine WT is a florescent dye commonly used in many water tracing studies (EPA etc.) and makes the direction of the water flow and its dilution visually clear.
However, Rhodamine WT's florescence is detected by the chl $\alpha$ sensors, so we could not use Rhodamine WT traces to check the water flow during experimental trials, and had to be sure pre-experiment Rhodamine WT traces completely cleared the study area. 
Second, we assumed that water depth and velocity remained constant through the trial and habitat. 
Both depth and velocity were measured several times through out a trial and averaged for calculation simplicity. 
Third, we assumed a well mixed water column.

Fluid dynamic are complex along rugous habitats - 'vertical gradients' in velocity and and particle concentration ((Nowell and Ju- mars 1984; Muschenheim 1987 in @Monismith1990). We positioned our instruments at the hight of the oyster habitat to measure address this habiat layer depletion (@Grizzle2008)

Slow water flows causes suspended solids to settle out of the water column (separate citation needed) leading ot food depletion for downstream filter-feeders (Monismith et al 1990 only looked at siphon feeders in @Harsh1999).
In addition, Harsh and Luckenbach (-@Harsh1999) found that the texture of oyster habitat causes varied hydrodynamics and particle redistribution in the water column.
Our water velocities were relatively slow, and at risk for uneven food availability across the habitat (Monismith et al 1990 in @Harsh1999).
However, the water dynamics in shallow estuaries often mix the wate rcolumn, amelerating chlorophyll stratification (Holligan et al. 1984 cited in @Judge1993) (Add Officer 1982 & Fredett 1989 in @Harsh1999?)

Habitat Clearance Rates differ from individual bivalve clearance rates, as they inherently include variables that complicate individual filtration models. 
Bivalve oreientation relative to water flow direcction can affect individual filtration rates (citations).
Bivalves growing in a natural community are position every which way. While flow firection and speed may inhibit some individuals or species feeding, others may be more optimally positioned. 
By measuring the whole habiatt, we are incorporating and averaging individual bivalve's feeding responses to environmentals conditions, and resolve the issue of expanding individual filtration rates to habitat leverls (see Cranford et al. 2011).

All experimental trials were conducted at a depth less than 0.9 m (Table 1), San Rafael was recorded at the deepest depth because of the vertical relief of the oyster reefs, all other sites were less than 0.5 m.

### Outline

* Restate research goals
  + In situ whole-habitat measurements
    - filter feeding community - move beyond single-species estimates
    - dynamic environmental conditons 
  + Filtration services of restored *O. lurida* 
  + Filtration services of *C. gigas* aquaculture
  
* Assumptions / Data Description
  + Instruments measuring same mass of water
    - each site required several days in the field - RWT observations
    - RWT couldn't be used during the trial - measured by Chl sensors
  + Well mixed water column
  + HCR values
    - Individual feeding behavior - averaged response to environmental conditions (flow direction & predation)
    - time averaged (talk about trial durations)
    - tide restricted when measurements could be taken (Wheat & Ruesink talk about depth)
    
* Control vs. Oyster habitat stats
  + contextualize t-test. Went from sig to no sig
  + small sample size, p-values aren't the whole story
  + practically, we see a suggested difference in Chl drawdown 
  
* HCR ~ WQ + Site
  + Benefits of Random Forest
    - Don't need to worry about covariance among parameters
    - allows us to use all of our data
  + Compare to previous research
    - Literature - our parameters are all important to filtration 
    - RF doesn't spell out specific relationships
    - We can rank the parameters - in line with previous research
  + Demonstrate filtration with limited data set
  + More data - better
  + Didn't include a quantitative biomass parameter - not enough data
  
* Biomass Estimates
  + Direct biomass measurements are time consuming 
  + Shell length:DTW models are practical estimations 
  + Regional allometric relationship? Or bigger data set - better relationship?
  + Olympia oyster model presented here can be used without sacrificing animals
* Future Directions
  + These methods are limiting
    - expensive
    - time consuming
    - subject to disturbance
    - site access issues 
  + floating / single instrument methods
    - More practical for individual restoration projects to monitor filtration services
    - Wheat & Ruesink 2013
    - Grizzle et al. 2018
    - Spatial component - how far filtration services affect water
    - increase temporal range (not restricted by linear water flow and tide cycles)
  + Spatially explicit models
    - Gray et al. 2019 - FVCOM; Lemagie & Lerczak (2015)
    - Found *O. lurda* can filter much larger part of Yaquina Bay then previously estimated (zu Ermgassen 2013)
    - Season, scale of restoration, locations within estuary important to filtration services
    - unique to bay hydrodynamics - residence time 
    - effeciently direct retoration for filtration / food availability


### Theme - take home sentence

Filtration estimates of oyster habitat on the west coast need measurements that incorporate the entire filter-feeding community of constructed oyster restorations and commercial aquaculture.
  
### Incorporate these tidbits?

* Chl $\alpha$ - proxy for photosynthetic organic material - Check @Secor2006 for ideas
* Higher organic content means a higher proportion of digestible food, which increases clearance rates (@Gray2018). [read Bayne et al. 1989; Barillé et al. 1997; Hawkins et al. 1998a; Bayne 2002; Ward and Shumway 2004)]. 


```{r Extra_Text, eval=FALSE, include=FALSE}
## Long Form Introduction  --> Save for discussion

### Natural History 

The Olympia oyster (*Ostrea lurida*) has inhabited California estuaries since the late Miocene and early Pliocene [@Arnold1909; @Howard1935] and is currently the only native oyster to the North American Pacific coast from British Columbia, Canada [@Polson2009] to Baja California, Mexico [@Raith2016].
*O. lurida* is considered a foundation species [@Dayton1972] in estuarine ecosystems because of the complex biogenic habitat they create. 
When spawning, *O. lurida* spermatozoa is filtered from the water column and transported to the mantle cavity where the eggs are fertilized and develop into veliger larvae [@Coe1932a]. 
Veligers are released into the water column and seek out hard substrate to settle and grow on, often other oyster shells [@Prytherch1931].
This behavior forms three dimensional structures known as beds or reefs depending on the extent of physical relief ( >0.5m : reef, < 0.5m ; bed per [@Beck2009]).
The conglomerate of living and dead shells creates complex habitat for a multitude of invertebrates, juvenile fishes and feeding habitat for birds and larger fishes [@Coen2007; @Peterson2003], and is thought to provide protection against shoreline erosion by diminishing wave energy in low energy environments like estuaries and bays [@Meyer1997; @Piazza2005; @Scyphers2011].
Indigenous peoples along the coast often lived close to these productive *O. lurida* beds, where middens indicate *O. lurida* was abundant and a substantial component of indigenous peoples'' diets [@Merlin1977; @Elsasser1966; @Barner1981; @Kidd1967; @Nelson1909] as early as 3,500 years ago [@Gifford1916].

### Filtration Services

Oyster beds also provides filtration services as *O. lurida* and the suite of other organisms that recruit to oyster habitat (i.e. mussels, tunicates, scallops, and sponges) are suspension feeders. 
Suspended phytoplankton, bacteria, algae, and sediments are removed from the water column by benthic suspension feeders, foodstuff digested, and unused matter is deposited in the benthos [@Baird1989; @Dame1999] thus increasing water clarity [@Newell2004b; @Grizzle2008] (and enriching benthic sediments?) useful to benthic primary producers, like seagrasses [@Peterson1999]. 

### Olympia Decline & Non-native Oysters

Overfishing in concert with destructive fishing practices [@Kirby2004], introduction of non-native species [@Bonnot1935], pollution, and excessive sedimentation [@Hopkins1931; @Lotze2006; @Nelson1909] have reduced *O. lurida* populations to less than 90% of historical abundances in parts of the Pacific Northwest, and to less than 99% in the rest of its geographic distribution [@Beck2011; @ZuErmgassen2012]. (reduced populations and inhibit pop recovery perhaps, could include more citations from Ruesink 2005, Lotze 2006, Jackson 2001)
Settlers of European descent commercialized *O. lurida* harvests in the early 1800s in San Francisco Bay, CA [@Conte1982] and the fishery subsequently followed a linear collapse pattern up the coast from San Francisco [@Kirby2004].
*O. lurida* was quickly overfished following the massive population influx to California during the Gold Rush starting in 1848 (Beattie, McMillin & Wiegardt 1982 in Kirby 2004, waiting for ILL pdf). 
In turn, the market transitioned to imparting *O. lurida* from estuaries up to Washington State until 1869 [@Kirby2004; more!], when the transcontinental Central Pacific Railroad was completed [@Conte1982].
Railroad shipments of Eastern oysters (*Crassostrea virginica*) were introduced to the San Francisco Bay [@Galtsoff1929] and accounted for about 80% of the market in the late 1800s and early 1900s [@Conte1982].
Simultaneously, San Francisco Bay intertidal habitats were smothered by an estimated 876 million cubic meters of sediment washed into the bay from hydraulic gold mining in the Sierra Nevada mountains [@Gilbert1917]. 
A second non-native oyster, the Japanese oyster (*Crassostrea gigas*), was successfully cultivated in the Salish Sea in the early 1920s [@Quayle1988] and introduced to California in 1928 [@Conte1982].
*C. gigas* now accounts for the overwhelming majority of commercial oyster harvest on the North American west coast (need citation), and has established feral populations outside of aquaculture operations in the Salish Sea [@Quayle1988;], Willipa Bay, WA [@Kincaid1968], and Southern California [@Crooks2015a; @Polson2009; @Tronske2018].

### Loss of Ecosystem Services

The extreme reduction of native *O. lurida* abundances is coupled with the loss of important complex habitat, adjacent shoreline stabilization, and water filtration functions.
Restoring this suite of ecosystem functions is part of the impetus behind native *O. lurida* restoration efforts along the west coast [@Dinnel2009; @Henderson2015b; @Latta2015; @Wasson2015; @Zacherl2015a]. 
However, the filtration capacity of *O. lurida*, even at historic abundances, is in question for several reasons (need zu Ermgassen 2013 citation?).
First, *O. lurida* has a relatively small body size, adults range from 15-45mm in length (find real # and citation), and body size is positively related to clearance rate [@Cranford2011].
Second, *O. lurida*''s gill structure may not be efficient at capturing small particles because of its relatively large gill ostia (90-180 $\mu$m height, 45-60 $\mu$m wide; @Elsey1935) that allows water to flow through the particle capturing filaments and into the inner water canal [@Bayne2017].
Third, most west coast bay and estuaries where *O. lurida* resides have low average residence times [citations in zu Ermgassen 2013], thus the water quality and phytoplankton community are predominantly oceanic influenced [@ZuErmgassen2013c].

### Other Filtration Factors

While these factors may restrict *O. lurida*''s water filtration capacity, it is also necessary to consider the following factors when thinking about the filtration capacity of *O. lurida* habitat:
1) *O. lurida* beds are complex habitat used by other filter feeding organisms (i.e. mussels, tunicates, scallops, and sponges) that may substantially contribute to net filtration.
Filter-feeding species are documented to have species-specific feeding behaviors (citations in Gray & Langdon 2018), thus filtration capacity may vary with different community compositions on *O. lurida* habitat.
2) Environmental conditions like temperature [@Gray2018; @ZuErmgassen2013c], seston organic content [@Gray2018; @Kreeger2001], salinity [@Gray2018], and water velocity [@Grizzle1992; @Harsh1999] are all known to affect bivalve filtration rates, are unique to each water body, and again could contribute to a unique filtration signature.
3) *O. lurida* habitat may have stronger influence over water quality in back reaches of bays where the residence time can be substantially longer than the bay''s average.
4) Oyster culture operations raising non-native *C. gigas* are present in many west coast bays, and should be considered when estimating the bay-wide filtration services provided by oyster habitat.
*C. gigas* is a faster growing and larger oyster than *O. lurida* with a higher filtration rate [@Bougrier1995; @ZuErmgassen2013c; @Gray2018; @Gray2019] that is documented to decrease chlorophyll concentrations in Willipa Bay, WA [@Wheat2013].

### Previous Research & Need for in situ Study

During the in situ trials, individual oyster were placed in a flow through chamber filled with ambient seawater from Yaquina Bay, Oregon at a rate of 150-200 ml min^-1^, and individuals not filtering (closed valve) were excluded from the analysis [see @Cranford2011].

Several studies lay the ground work of estimating the filtration services of *O. lurida* habitat and cultured *C. gigas* in west coast bays, but leave room for further in situ investigations.
@ZuErmgassen2013c calculated filtration rates (L/hr/g dry tissue weight) of *O. lurida* and *C. gigas* over a range of temperatures and oyster sizes in the laboratory. 
@Gray2018 expanded on this work and determined the filtration rates (L/hr/g DTW) of *O. lurida* and *C. gigas* under ranges of temperature, salinity, Total Particulate Matter (TPM), and Organic Content (OC). Laboratory and in situ trials were included in this study using the biodeposition method [@Hawkins1996] to calculate filtration. 
However, both studies measured filtration in a single species context, and all oysters were from Coos Bay, OR and Yaquina Bay, OR.
Thus, estimating the filtration capacity of restored *O. lurida* habitat with these filtration models has limited application, and needs field verification before using in other regional locations.

Laboratory studies can not account for the myriad of interacting environmental conditions that potentially effect the filtration capacity of a specific oyster bed [@Gray2018 cites Cranford and Hill 1999; @Grizzle2008; @Cranford2011]. --> Reword to something along the lines of needing to "move beyond laboratory based oyster-only feeding rates to more ecologically realistic field studies of how oyster reefs affect ecosystem processes (Grizzle et al. 2018 quote, includes list of citations)

First, species-specific feeding behavior is well documented [@Møhlenberg1979; @Riisgard1988; @Riisgard2001; Cranford2011] and can vary depending on spatial and temporal environmental conditions [@Moody2020a; Cranford1999] (citations in @Gray2018). 

Texture of habitat leads to varied hydrodynamics and mixing (Harsh & Luckenback 1999) that can effect environmental that mediate filtration.
Slow flow can lead to food depletion to downstream animals (Monismith et al 1990 in Harsh & Luckenbach1999).
Higher flows can redistribute particles throughout the water column replenishing food for bivalve filter feeders ( Officer 1982 & Fredett 1989 in Harsh & Lauckenbach1999)
Water dynamics in shallow estuaries often mixes water column "eliminating stratification of chlorophyll (Holligan et al. 1984 cited in @Judge1993).
Deeper waters might limit the access that benthic bivalves have to food (citations in @Ruesink2005).
Orientation of oyster relative to flow effect feeding behavior [@Grizzle1992; @Harsh1999].
Laboratory studies often don't include oysters not feeding, closed valves, resulting in artificially high filtration rates [@Gray2018; @Harsh1999], and may partly explain why many field studies find lower FR than laboratory studies [@Gray2018 cited Newell 2005; @Grizzle2008; @Cranford2011].
In situ studies may not be able to produce the sophisticated models based on manipulated variables, but can record the range of Filtration capacity of a specific restoration or aquaculture operation within its complex environment.

The objective of this study was to identify...

##Extra Text
	
This and many other studies use chlorophyll $\alpha$ as a metric for filtration (Luckenbach and Harsh 1999; Wasson et al. 2015; Grizzle, Greene, and Coen 2008; Grizzle et al. 2006) because chlorophyll $\alpha$ is a plant pigment whose concentration is a proxy for phytoplankton and algae fragments consumed by filter feeders [Is this the right place for this Chl info?]. 
In summary, filtration models of oyster habitat lack in situ comparisons that incorporate complex environmental conditions and other bivalve contributions to overall filtration function of restored *O. lurida* habitat and C. gigas aquaculture. 
My research uses in situ methods based on Grizzle et al. (2006 & 2008) and Milbrandt et al. (2015) to test previous filtration models, using restored and aquaculture oyster habitat.

Oyster habitat provides myriad ecosystem services, such as water filtration, to bays and estuaries worldwide. Laboratory and limited in-situ studies have provided initial estimates of the filtration services provided by the U.S. West Coast’s only native oyster,  Ostrea lurida, but refined field-based estimates that consider multiple biological and physical factors are sorely needed. 

Two studies based in Yaquina Bay, Oregon provide a strong foundation for estimating O. lurida filtration rates (zu Ermgassen, Gray, et al. 2013, Gray & Langdon 2017), but several important factors useful for estimating filtration rates remain underexplored.  Previous filtration studies were conducted in the laboratory or were single-species, in-situ studies (zu Ermgassen, Gray, et al. 2013, Gray & Langdon 2017), while O. lurida beds are complex habitat used by other filter feeding organisms (i.e. C. gigas, mussels, tunicates, scallops, and sponges) that may substantially contribute to overall filtration. Further, O. lurida habitat contains differing filter feeder communities across estuaries; San Francisco Bay does not have a feral C. gigas population, while Newport and San Diego Bays contain abundant C. gigas. Next, environmental conditions of estuaries vary greatly in space and time and previous studies have only focused on limited field conditions in Yaquina Bay, Oregon with isolated O. lurida (Gray & Langdon 2017). Residence time, temperature, turbidity, food availability, salinity, emersion time, and water flow speed are all parameters known to affect bivalve filter feeding rates, and will be unique to each California estuary. Thus, previous filtration estimates are not directly applicable to existing restoration and aquaculture operations in California.

Native O. lurida and non-native C. gigas may overlap in ecological services like filtration. However, physiological differences between the oyster species may change the degree of their respective filtration services. Gray & Langdon (2017) point out that O. lurida selects larger particles from the water column compared to C. gigas, likely because of anatomical differences in gill ostea, which may differentiate the quality of filtration by each species. C. gigas is also faster growing, larger, and has a greater filtration rate than O. lurida (zu Ermgassen, Gray, et al. 2013, Gray & Langdon 2017), but feral populations of C. gigas in Newport and San Diego Bays experience significantly less immersion time than O. lurida due to an observed zonation pattern between the species. C. gigas settles and grows at higher tidal elevations (+1 to +3.5 ft MLLW), and is thus immersed in the water column for a shorter duration than O. lurida, which settles and grows at lower tidal elevations (-1 ft MLLW to +1 ft MLLW) (Zacherl, ms submitted); each species is also associated with an entirely different filter-feeding community at their respective tidal elevations.  Although feral C. gigas is immersed for shorter durations than O. lurida in Newport Bay and San Diego Bay, research in Willapa Bay, Washington showed that seston and phytoplankton were regulated top-down by commercially grown C. gigas (Wheat & Ruesink 2013), thus C. gigas may play a substantial role in overall water filtration in California estuaries, particularly when associated with aquaculture operations in Morro Bay, Agua Hedionda, and San Diego Bay.

Water residence time, and the presence of aquaculture operations are other factors that will affect overall oyster filtration capacity. California bays typically have low average residence times, so zu Ermgassen, Gray, et al. (2013) speculate that oysters may only affect seston and phytoplankton concentrations in the back portions of such bays and estuaries where residence times increases, and thus where oysters and other filter feeders may impact water quality. Evidence from Wheat & Ruesink (2013) and Gray & Langdon (2017) suggests that C. gigas aquaculture operations located in the inner reaches of California’s bays and estuaries may play a role in returning filtration services lost from decimated O. lurida populations. 

The Nature Conservancy (TNC) and the National Oceanic and Atmospheric Administration (NOAA) published a Manager's guide (zu Ermgassen et al. 2016) that includes several models to estimate the quantity of ecosystem services provided by restored oyster habitat. Filtration of *O. lurida* habitat is calculated using data from a single laboratory study (zu Ermgassen et al., 2013), while the eastern oyster (Crassostrea virginica) filtration model uses a combination of laboratory and in situ data. In situ filtration rates of *O. lurida* habitat are important to estimate filtration functions under complex environmental conditions often difficult to simulate in a laboratory setting. Gray and Langdon (2017) measured in situ filtration of isolated *O. lurida* in Yaquina Bay, Oregon, providing a foundation for estimating in situ *O. lurida* filtration rates. However, three factors important to filtration remain underexplored.
```