---
title: "Methods"
author: "Althea Marks"
date: "1/28/2020"
output: pdf_document
---

# Methods
## Study Sites and Experimental Design

This research uses methods based on Grizzle et al. (2006); Grizzle, Greene and Coen (2008), and Mildbrandt et al. (2015)’s in situ measurement of bivalve reefs’ filtration rates on the Atlantic coast. The entire filter feeding community residing in the oyster habitat are included in these filtration measurements, while operating under ambient environmental conditions. Grizzle et al. (2008)’s results inform oyster habitat filtration models for the Atlantic and Gulf coasts in the National Oceans and Atmopsheric Administration's (NOAA) and The Nature Concervancy's "A Manager's Guide: Setting Objectives for Oyster Habitat Restoration Using Ecosystem Services" zu Ermgassen et al. (2016). My research aims to inform the Pacific coast oyster habitat filtration model using similar methods. 

Two constructed Ostrea lurida restoration sites and one Crassostrea gigas aquaculture opperation were included in this study. The San Francisco Living Shorelines Project was constructed in the summer of 2012 in collaboration by UC Davis, The Coastal Conservancy, The Smithsonian XXXX etc. The project has two major sites on different sides of the San Francisco bay, San Rafael and Hayward. The San Rafael (hensforth San Rafael) site was chosen for its accessability and relatively higher abundances of Ostrea lurida. San Rafael consists of a matrix of shell bag mounds with a total 32 m x 10 m footprint consisting of 3 rows of 8 shell bag mounds (“San Francisco Bay Living Shorelines Project Physical Properties Report, Novemeber 2014” 2014). Each mound measures 2 m2 and is composed of 4 shell bag elements measuring 1 m2. A shell bag consists of plastic mesh filled with clean commercially grown Crassostrea gigas shell. The restoration matrix is positioned about 200 m from shore on a mudflat at -0.3 m MLLW tidal evlevation (“San Francisco Bay Living Shorelines Project Physical Properties Report, Novemeber 2014” 2014). 

The Upper Newport Bay Living Shorelines Project, Newport Bay, California was constructed in May 2017. The project consists of 4 sites, Pacfic Coast Highway, Westcliff, Deanza, and Shellmaker. This study only includes Deanza (hensforth Newport Deanza) and Shellmaker (hensforth Newport Shellmaker) because of their accessibility, water flow dynamics, and relatively higher abundances of Ostrea lurida. Each sites has a 4 plots made up of on control mudflat, Zostrea marina transplant beds, and shell beds. The shell beds measure 20m x 1m and are constructed coconut coir bogs filled with clean Crassostrea gigas and mussel ### species name? shell. The beds are positioned about 30m from shore on a frim mudflat at approximately 0.15 m MLLW (Mean Low Lower Water).

The Morro Bay Oyster Company (MBOC) is a commercial aquaculture operation in Morro Bay, Califonia (hensforth Morro Bay). MBOC grows Crassostrea gigas in plastic mesh bags attached to about 20 floating lines that stretch a 75m x 75m area. The bags rest on the underlying mudflat at around 0 m MLLW, and float to the surface as the tide rises. 



Two identical water quality sondes (Yellow Springs Instruments 6600EDS) both equipped with chlorophyll a, temperature, salinity, and turbidity sensors are hung inside of free standing PVC housings. The sensors are positioned to align with the approximate height of the oyster habitat. The sondes are placed upstream and downstream of the oyster habitat. A non-toxic water tracing dye (Rhodamine WT) is released at the upstream sonde position to verify the water flows over the oyster habitat and subsequently over the downstream sonde. The dye is also a visual indicator of any cross currents or eddies in the water flow path that could confound filtration results. Once the sondes are positioned accordingly, an electromagnetic meter (Marsh McBirney Flo Mate 2000) measures water velocity at each sonde and in the center of the habitat at the depth of the sensors, and the distance between sondes is noted. Water velocity and water column depth measurements are taken just before the filtration trial begins, in the middle of the trial, and just after the filtration trial ends. Sondes are set to take measurements every 1 second and a typical filtration trial lasts as long as the correct field conditions last, between 10 and 30 minutes. A second side-by-side trial is conducted shortly after the filtration trial. A watch synced with the sondes is used to take detailed notes of all field events including side-by-side start and finish, velocity measurements, water samples for seston organic content analysis, filtration trail start and finish, and any disturbances such as boat wake or the sonde housings falling over. 

Prior to the filtration trial, the sondes in the housings are placed side-by-side for a period of time (ranging from 5 to 10 mins) to ensure that the sensors are reading similar numbers in the same water. This side-by-side measurement is used to correct sensors, if necessary, before calculating filtration. 



Ideal conditions for these filtration methods include: 1) linear water flow across the habitat, 2) slow water velocity (between 0.1 – 0.3 m/s) to not resuspend benthic sediments into the water column, 3) shallow water depths where the habitat is completely submerged but has the greatest relative filtration impact on the water column seston, and 4) little to no wind, as strong winds can generate currents that resuspend benthic sediments into the water column. Resuspended benthic sediments confound the sonde measurements and make it impossible to examine the effect the oyster habitat filtration has on the water column (Grizzle et al. 2006 & 2008). Ideal conditions are often met on either side of a low tide depending on the site. 

The ratio of organic to inorganic content of seston is an important factor in bivalve clearance rates (Gray and Langdon 2017). Three 1L water samples are collected in opaque Nalgene bottles adjacent to the upstream sonde during the filtration trial. The water samples are either stored on ice for transport or immediately filtered through Whatman GF/F pre-washed and weighed filters and placed on ice. The filters are stored in the freezer until processing. The filters are thawed and rinsed with Ammonium Formate to remove salt and then dried in an 60C oven for 48 hours. The weight of the dried filter is used to calculate total particulate matter (TPM; g/L). Next the filters are combusted at 600C for at least 4 hours and weighed to calculate particulate inorganic matter (PIM; g/L). The difference of TPM and POM is the particulate organic matter (POM; g/L).

Filtration Calculation

Detailed field notes with corresponding time stamps are used to trim the raw data produced by the sondes into side-by-side and filtration trials. Average water velocity and distance between the sondes is used to pair upstream and downstream measurements. The paired chlorophyll  measurements are then used to calculate percent chlorophyll removal (Equation 1) and habitat level filtration rate (Equation 2). Chlorophyll removal is simply percent change in chlorophyll  concentration from the upstream to downstream sonde and is used for intra-site filtration comparisons. The habitat level filtration rate takes into account the water column depth, water velocity, and habitat area relative to the change in chlorophyll  to produce a measurement of Lhr-1m-2, and is used for inter-site filtration comparisons.

Equation 1:     (〖Chl〗_up-〖Chl〗_down)/〖Chl〗_up *100=  % Chl α removal

Equation 1: The percent chlorophyll  drawdown from the upstream sonde to the downstream sonde, where Chlup = upstream sonde [chl ] and Chldown = downstream sonde [chl ] (Grizzle et al. 2008).     

Equation 2:  ([A_xsec  * v *1000])/A_habitat *([〖Chl〗_up-〖Chl〗_down])/〖Chl〗_up   = L hr-1 m-2

Equation 2: Habitat level filtration rate from Mildbrandt et al. (2015), where A_xsec= cross section of habitat (1m x depth (m) = m2), v = water flow velocity (mhr-1), A_habitat= habitat area (distance between sondes (m) x average width of habitat (m) = m2), 1000 = conversion factor from m2 to L, 〖Chl〗_up = upstream chlorophyll α (𝜇g/L), 〖Chl〗_down = downstream chlorophyll α (𝜇g/L).

Description of Sites 

This research is conducted at four sites, two are constructed Ostrea lurida habitats in Upper Newport Bay, CA (henceforth Newport Deanza) and San Francisco Bay, CA (henceforth San Rafael). The other two sites are Crassostrea gigas aquaculture operations in Morro Bay, CA (henceforth Morro Bay) and San Diego Bay, CA (henceforth San Diego). 

San Rafael consists of a 32 m x 10 m grid of shell bag mounds, which consists 24 shell bag mounds. Each mound measures 4 m2 and is composed of 4 shell bag elements measuring 1 m2. The grid is positioned at -0.3 m MLLW about 200 m from shore on a mudflat (San Francisco Bay Living Shorelines Project Physical Properties Report, November 2014, 2014). 

 

The San Diego site is a FLoating UPwelling SYstem (FLUPSY) aquaculture structure operated by the Port of San Diego Blue Economy Incubator Program. A FLUPSY is an upwelling system that pulls water up through baskets submerged at the water surface. The upwelling provides juvenile oysters with a continuous supply of food from the surrounding water. The San Diego site requires modified methods to measure filtration. The upstream sonde is hung off the FLUPSY at the depth of the basket bottom and the downstream sonde is placed at the basket outflow channel. The operation of this FLUPSY has been episodic during my study to date and it is uncertain if operation will continue.  

My original proposal included a high-density natural Ostrea lurida bed on Vancouver Island, British Columbia. This site was removed from this study because of the difficult logistics to access the site. I am in touch with Canadian scientists monitoring the site, and may have an opportunity to assist them in future summer surveys. However, for the purposes of my graduate thesis I will not include this site.


NSA - Research Grant App

Methods are based off Grizzle et al. (2006)’s success in measuring in-situ filtration of bivalve reefs on the East Coast. We will measure chlorophyll  concentrations (hereafter [chl ]) upstream and downstream of constructed oyster habitat, as well as a suite of abiotic factors that may affect filtration (e.g., seston concentration (Grizzle et al. 1992), temperature (zu Ermgassen, Gray, et al. 2013, Gray & Langdon 2017), and flow speed (Grizzle et al. 2008)). Chl  is a plant pigment whose concentration is a proxy for phytoplankton consumed by filter feeders (Wasson et al. 2015) and a standard metric for oyster filtration studies (e.g. Grizzle et al. 2006, 2008, Wheat & Ruesink 2013, zu Ermgassen, Gray & Langdon 2017). Two identical YSI 6600EDS water quality sondes (loaned by San Francisco National Estuarine Research Reserve and outfitted with temperature, salinity, chl , and turbidity sensors purchased by PI Zacherl) will be deployed simultaneously. One sonde will be placed upstream and the other directly downstream of the oyster habitat to measure the change in [chl ] every 10 seconds for 90 mins. The difference between the downstream and upstream [chl ] represents the seston removal of filter feeders. We will measure seston removal on restored Olympia oyster habitat in San Francisco Bay and Newport Bay, as well as aquaculture operations in San Diego Bay each during three different neap tide series for four consecutive days in Spring and Summer 2018 (see Milestones Chart). We will also record positive and negative control measurements in San Diego Bay, and, as needed, at aquaculture operations in Agua Hedionda or Morro Bay. Filter feeder species richness, density, and shell height at each study site will also be measured by using replicate (n=10-15) haphazardly placed 0.25m2 quadrats and calipers.

Measurement of filtration rate requires linear flow dynamics over the oyster habitat to ensure that the downstream instrument measures the same water mass as the upstream instrument. A biodegradable fluorescent dye approved by the EPA (Environmental Protection Agency) will be released upstream from the site to ensure side or back flow does not disrupt the filtered water flow between the instruments. A GoPro camera secured to a long overhead pole will record the dye release for additional review, and a Marsh-McBirney electromagnetic flow meter (on loan from Dr. Ted Grosholz, committee member for Althea Marks) will measure flow velocity. Multiple dye releases may be needed to identify an optimal tidal cycle (ebb, flood, slack) and tidal elevation to record filtration measurements.

These methods were originally designed for shellfish beds on the East Coast; two features of O. lurida require us to perform a positive control for the proposed methods. O. lurida have a lower filtration rate compared to larger species such as C. gigas and C. virginica (zu Ermgassen, Gray, et al. 2013, Gray & Langdon 2017), and grow in smaller, less dense beds then the reefs formed by Crassostrea species (Beck et al. 2009). The positive control experiment will have identical methods but use high-density aquaculture structures (in Agua Hedionda Lagoon and San Diego Bay) as the measured habitat to ensure that our instrumentation can detect chl  removal in situ. Results of the positive control will be immediately useful to the Port of San Diego. The business incubator program is currently investigating the viability of raising C. gigas for export to other aquaculture operations. Among the variables they are investigating, the Port is interested in the environmental impact that an aquaculture business would have on the bay. Our data would provide them with filtration rates applicable to their potential operations. We also plan measures of filtration capacity of their planned FLUPSY structures. Paula Sylvia, Program manager of Aquaculture and Blue Technology at the Port, has confirmed that our positive control data and our direct measures of their operations will be directly transferable and useful to the Aquaculture Business Incubator Program. This collaboration also parallels California Sea Grant’s goals to “provide science-based information to support and grow a sustainable California aquaculture industry to help meet the growing demand of seafood and minimize negative environmental impacts of aquaculture.”

