---
title: IN SITU CLEARANCE RATES OF OLYMPIA OYSTER (*OSTREA LURIDA*) HABITAT AND PACIFIC
  OYSTER (*CRASSOSTREA GIGAS*) AQUACULTURE IN CALIFORNIA
author: "Althea N. Marks"
date: "Fall 2020"
output:
  pdf_document:
    fig_caption: yes
    latex_engine: xelatex
classoptions: 12pt,titlepage
documentclass: article
geometry: left=1.5in, right=1in, top=1in, bottom=1in
header-includes:
- \usepackage{placeins}
- \usepackage{setspace}
- \usepackage{booktabs}
- \usepackage{caption}
- \doublespacing
- \usepackage{lineno}
- \usepackage{makecell}
- \usepackage{gensymb}
- \usepackage{pdfpages}
- \setlength{\parindent}{4em}
- \setlength{\parskip}{0em}
- \usepackage{caption}
indent: yes
csl: marine-ecology-progress-series.csl
bibliography: library.bib
---

```{r include=FALSE}
knitr::opts_chunk$set(fig.path = 'figures/', 
                      echo = FALSE, warning = FALSE, message = FALSE)
```

```{r include=FALSE}
library()
```

\pagenumbering{gobble}
\titlepage
\pagenumbering{arabic} 
\clearpage

```{r child = 'Thesis_Abstract.Rmd'}
```

\newpage

\tableofcontents
\newpage 

\listoffigures
\newpage 

```{r child = 'Thesis_Acknowledgments.Rmd'}
```

\newpage

```{r child = 'Thesis_Introduction.Rmd'}
```

\newpage 

```{r child = 'Thesis_Methods.Rmd'}
```

\FloatBarrier
\newpage 

```{r child = 'Thesis_Results.Rmd'}
```

\FloatBarrier
\clearpage

```{r child = 'Thesis_Discussion.Rmd'}
```

\FloatBarrier
\newpage 

# References

\setlength{\parindent}{-0.2in}
\setlength{\leftskip}{0.2in}
\setlength{\parskip}{8pt}
\noindent