---
title: "Oyster Insitu Filtration"
output: 
  flexdashboard::flex_dashboard:
    theme: yeti
    orientation: rows
editor_options: 
  chunk_output_type: console
---


```{r setup}

## Import the libraries and functions
library(dplyr)
library(data.table)
library(magrittr)
library(lubridate)
library(ggplot2)
library(ggthemes)
library(stringr)
library(hms)

######################################################################
## settings: 
#1) data_directory: Keep only the input csv time series data in this directory
#2) velocity_data_directory : Additional files required to pair filtration time stamps by Velocity to be kept here
#3) manual_correction_directory: Put the manual correction files here. Can be the same as velocity_data_directory
#4) output_directory: This is the directory where the output will be created 
#5) code_directory : The directory where this code and the functions file are stored
######################################################################

data_directory = "./data_time_series"
velocity_data_directory = "./data_velocity_depth_etc"
manual_correction_directory = "./manual_corrections"
output_directory = "./output"



######################################################################
# Source/import required files 
######################################################################

# Create the required output directories
createOutputDirectories()

# Import the files related to water velocity measurements 
water_vel_df = fread(file.path(velocity_data_directory, "Insitu_Filter_velocity_all_data.csv"))
  
water_vel_other_var_df = fread(file.path(velocity_data_directory, "Insitu_Filter_sbs_FR_variables_all_data.csv"))

water_vel_summary = calculateTravelTimeBySiteAndDate(water_vel_df, water_vel_other_var_df)

# Import the manual corrections file
manual_correction_df = fread(file.path(manual_correction_directory, "Manual_Corrections.csv"))

manual_correction_df %<>%
  dplyr::mutate(Correction_Start_Time = as.hms(Correction_Start_Time),
                Correction_End_Time   = as.hms(Correction_End_Time))
```


Plots Before Corrections
=====================================

### 

```{r, fig.width=13.5, fig.height=5}

######################################################################
##Steps 1 to 4) read the files to standardize names and plot time series for sondes
######################################################################
all_files = list.files(data_directory, pattern = ".csv")

# Loop through files to standardize names and plot graph
for(file in 1 : length(all_files))
{
  file_name = all_files[file]
  
  # 1) Import the file
  one_file = fread(file.path(data_directory, file_name))
  
  #2 & 3) standardize name of columns and values
  one_file = standardizeNamesAndColumns(one_file)
 
  # 4) Plot the graph 
  plot(createTimeSeriesPlot(one_file, file_name))
  
  ## save the modified file 
  fwrite(one_file, file.path(output_dir_file_cleaning, file_name))
  
}
```

Plots After Corrections
=====================================

### 

```{r, fig.width=13.5, fig.height=5}
######################################################################
##Step 5 to 8)  Apply manual, Sbs corrections and calculate filtration
######################################################################
# empty data frame to store sbs correction summary  
sbs_correction_summary = data.frame()


#loop through files and apply manual corrections
for(file in 1 : length(all_files))
{

######################################################################
##Step 5)  Apply manual corrections
######################################################################
    
  file_name = all_files[file]
    
  # Import the file
  one_file = fread(file.path(output_dir_file_cleaning, file_name))
    
  ## apply manual corrections
  one_file = applyManualCorrections(one_file, file_name, manual_correction_df, output_dir_manual_corrections)
    
  # plot the time series agains
  plot(createTimeSeriesPlot(one_file, file_name))
    
  fwrite(one_file, file.path(output_dir_manual_corrections, file_name))
  
######################################################################
##Step 6) Apply sbs corrections 
######################################################################
  
  # check if sbs correction is required and record the result
  sbs_summary_one_file = summarizeSbsCorrectionValues(one_file, file_name)
  sbs_correction_summary = rbind(sbs_summary_one_file, sbs_correction_summary)
  
  # apply the correction if required
  one_file =  applySbsCorrections(one_file, sbs_summary_one_file)
  
  # save the corrected file
  fwrite(one_file, file.path(sbs_correction_output_directory, file_name))
  
######################################################################
##Step 7 and 8) Water Velocity measurement and Filtration calculation
######################################################################
  one_file = adjustDownSondeTimeStamp(water_vel_summary, one_file)
  one_file = calculateFilterationForPairedData(one_file, water_vel_summary)

  # save the filtration calculations
  fwrite(one_file, file.path(filtration_calc_output_directory, file_name))

}

```

```{R}
# Save the correction summary
fwrite(sbs_correction_summary,file.path(sbs_summary_output_directory,
                                        "sbs_correction_summary.csv"))
  

```