---
title: "Insitu_Filter Graphs"
author: "Althea Marks"
date: "11/12/2019"
output:
  html_document: default
  pdf_document: default
---

```{r include=FALSE}
library(dplyr)
library(tidyr)
library(data.table)
library(magrittr)
library(lubridate)
library(ggplot2)
library(ggthemes)
library(stringr)
library(hms)
library(viridisLite)
library(forcats)
library(gridExtra)

Master_analysis_table <- fread(file.path('./Data', "Master_Filtration_analysis_table.csv"))
Avg_TPM_summary_table <- fread(file.path('./output/5_TPM_OC_Summary', "Avg_TPM_summary_table.csv"))
Density_directory = "./Data/bivalve_density_community"
NPD_density = fread(file.path(Density_directory, "Insitu_Filter_NPD_bivalve_biomass_data.csv"))

```

Filtration Rates (L/hr/m^2) predicted by Total Particulate Matter (ug/L) of seston
```{r FR vs TPM, echo=FALSE, message=FALSE}
Filter_data <- Master_analysis_table %>% 
                     filter(Experiment == "Filtration")

Filter_data_pos <- Master_analysis_table %>% 
                     filter(Experiment == "Filtration",
                            L_hr_m2 > 0)
# FR by site all data
(FR_TPM_box <- ggplot((Filter_data), aes(Site, L_hr_m2)) +
  geom_boxplot() +
  theme_classic() +
  labs(x = 'Site',
       y = 'Filtration Rate L/hr/m^2'))
# FR by site (Positive values only) 
(FR_TPM_box <- ggplot((Filter_data_pos), aes(Site, L_hr_m2)) +
  geom_boxplot() +
  theme_classic() +
  labs(x = 'Site',
       y = 'Filtration Rate L/hr/m^2'))

# FR vs TPM (Filtration Trials only)
(FR_TPM_graph <- ggplot((Filter_data), aes(Avg_TPM, L_hr_m2, color = Site)) +
  geom_point() +
  theme_classic() +
  labs(x = 'Total Particulate Matter (ug/L)',
       y = 'Clearence Rate (L/hr/m^2)',
       title = 'All Filtration Trials') +
  guides(fill = FALSE))

# Fit line 
(FR_TPM_lm_graph <- ggplot(Filter_data, aes(Avg_TPM, L_hr_m2)) +
  geom_point() +
  geom_smooth(method=lm, se=TRUE, level=0.95) +
  theme_classic() +
  labs(x = 'Total Particulate Matter (ug/L)',
       y = 'Clearence Rate (L/hr/m^2)',
       title = 'All Filtration Trials with lm') +
  guides(fill = FALSE))

FR_TPM_lm <- lm(data = Filter_data, L_hr_m2 ~ Avg_TPM)
summary(FR_TPM_lm)
par(mfrow=c(2,2))
plot(FR_TPM_lm)

```

Filtration Rates (L/hr/m^2) predicted by Organic Content of seston
```{r FR vs OC, echo=FALSE}
(FR_OC_graph <- ggplot(Filter_data, aes(Avg_OC_Ratio, L_hr_m2, color = Site)) +
  geom_point() +
  theme_classic() +
  labs(x = 'Organic Content of Seston (fraction)',
       y = 'Clearence Rate (L/hr/m^2)',
       title = 'All Filtration Trials') +
  guides(fill = FALSE))

(FR_OC_graph_bestfit <- ggplot(Filter_data, aes(Avg_OC_Ratio, L_hr_m2)) +
  geom_point() +
  theme_classic() +
  labs(x = 'Organic Content of Seston (fraction)',
       y = 'Clearence Rate (L/hr/m^2)',
       title = 'All Filtration Trials with best fit line') +
  guides(fill = FALSE) +
  geom_smooth(method=lm, se=TRUE, level=0.95))

FR_OC_lm <- lm(data = Filter_data, L_hr_m2 ~ Avg_OC_Ratio)
summary(FR_OC_lm)
par(mfrow=c(2,2))
plot(FR_OC_lm)

# Deanza only
(FR_OC_NPD_graph <- ggplot(Filter_data %>% 
                             filter(Site == "Deanza"),
                           aes(Avg_OC_Ratio, L_hr_m2)) +
  geom_point() +
  theme_classic() +
  labs(x = 'Organic Content of Seston (fraction)',
       y = 'Clearence Rate (L/hr/m^2)',
       title = 'Newport Deanza Filtration Trials with best fit line') +
  guides(fill = FALSE) +
  geom_smooth(method=lm, se=TRUE, level=0.95))

FR_OC_NPD_lm <- lm(data = (Filter_data %>% filter(Site == "Deanza")), L_hr_m2 ~ Avg_OC_Ratio)
summary(FR_OC_NPD_lm)
par(mfrow=c(2,2))
plot(FR_OC_NPD_lm)

# Morro Bay only
(FR_OC_MB_graph <- ggplot(Filter_data %>% 
                             filter(Site == "Morro Bay"),
                           aes(Avg_OC_Ratio, L_hr_m2)) +
  geom_point() +
  theme_classic() +
  labs(x = 'Organic Content of Seston (fraction)',
       y = 'Clearence Rate (L/hr/m^2)',
       title = 'Morro Bay Filtration Trials with lm') +
  guides(fill = FALSE) +
  geom_smooth(method=lm, se=TRUE, level=0.95))

FR_OC_MB_lm <- lm(data = (Filter_data %>% filter(Site == "Morro Bay")), L_hr_m2 ~ Avg_OC_Ratio)
summary(FR_OC_MB_lm)
par(mfrow=c(2,2))
plot(FR_OC_NPD_lm)

# San Rafael only
(FR_OC_NPSM_graph <- ggplot(Master_analysis_table %>% 
                             filter(Site == "San Rafael"),
                           aes(Avg_OC_Ratio, L_hr_m2)) +
  geom_point() +
  theme_classic() +
  labs(x = 'Organic Content of Seston (fraction)',
       y = 'Clearence Rate (L/hr/m^2)',
       title = 'San Rafael Filtration Trials with lm') +
  guides(fill = FALSE) +
  geom_smooth(method=lm, se=TRUE, level=0.95))

FR_OC_SR_lm <- lm(data = (Filter_data %>% filter(Site == "San Rafael")), L_hr_m2 ~ Avg_OC_Ratio)
summary(FR_OC_SR_lm)
par(mfrow=c(2,2))
plot(FR_OC_SR_lm)

# Shellmaker only
(FR_OC_NPSM_graph <- ggplot(Filter_data %>% 
                             filter(Site == "Shellmaker"),
                           aes(Avg_OC_Ratio, L_hr_m2)) +
  geom_point() +
  theme_classic() +
  labs(x = 'Organic Content of Seston (fraction)',
       y = 'Clearence Rate (L/hr/m^2)',
       title = 'Shellmaker Filtration Trials with lm') +
  guides(fill = FALSE) +
  geom_smooth(method=lm, se=TRUE, level=0.95))

FR_OC_NPSM_lm <- lm(data = (Filter_data %>% filter(Site == "Shellmaker")), L_hr_m2 ~ Avg_OC_Ratio)
summary(FR_OC_NPSM_lm)
par(mfrow=c(2,2))
plot(FR_OC_NPSM_lm)
```
Filtration Rate (L/hr/m^2) predicted by Temperature (Linear Model, 95% CI)
```{r FR vs Water Quality, echo=FALSE}

(FR_Temp <- ggplot(Filter_data, aes(Temp_C_Up, L_hr_m2, color = Site)) +
  geom_point() +
  theme_classic() +
  labs(x = 'Temperature Upstream (C)',
       y = 'Clearence Rate (L/hr/m^2)',
       title = 'Filtration predicted by Temprature - All Sites'))

(FR_Temp_bestfit <- ggplot(Filter_data, aes(Temp_C_Up, L_hr_m2)) +
  geom_point() +
  theme_classic() +
  labs(x = 'Temperature Upstream (C)',
       y = 'Clearence Rate (L/hr/m^2)',
       title = 'Filtration predicted by Temprature - All Sites') +
  geom_smooth(method=lm, se=TRUE, level=0.95))

FR_temp_lm <- lm(data = Filter_data, L_hr_m2 ~ Temp_C_Up)
summary(FR_temp_lm)
par(mfrow=c(2,2))
plot(FR_temp_lm)
```
Filtration Rate (L/hr/m^2) predicted by Salinity (Linear Model, 95% CI)
```{r echo=FALSE}

(FR_Sal <- ggplot(Filter_data, aes(Sal_ppt_Up, L_hr_m2, color = Site)) +
  geom_point() +
  theme_classic() +
  labs(x = 'Salinity Upstream (ppt)',
       y = 'Clearence Rate (L/hr/m^2)',
       title = 'Filtration predicted by Salinity - All Sites')) 
  
(FR_Sal_bestfit <- ggplot(Filter_data, aes(Sal_ppt_Up, L_hr_m2)) +
  geom_point() +
  theme_classic() +
  labs(x = 'Salinity Upstream (ppt)',
       y = 'Clearence Rate (L/hr/m^2)',
       title = 'Filtration predicted by Salinity - All Sites') +
  geom_smooth(method=lm, se=TRUE, level=0.95))

FR_Sal_lm <- lm(data = Filter_data, L_hr_m2 ~ Sal_ppt_Up)
summary(FR_Sal_lm)
par(mfrow=c(2,2))
plot(FR_Sal_lm)
```

```{r echo=FALSE}
# Chlorophyll 
(FR_Chl <- ggplot(Filter_data, aes(Chl_ug_L_Up, L_hr_m2, color = Site)) +
  geom_point() +
  theme_classic() +
  labs(x = 'Chlorophyll Upstream (ug/L)',
       y = 'Clearence Rate (L/hr/m^2)',
       title = 'Filtration predicted by Chlrophyll - All Sites')) 
  
(FR_Chl_bestfit <- ggplot(Filter_data, aes(Chl_ug_L_Up, L_hr_m2)) +
  geom_point() +
  theme_classic() +
  labs(x = 'Chlorophyll Upstream (ug/L)',
       y = 'Clearence Rate (L/hr/m^2)',
       title = 'Filtration predicted by Chlorophyll - All Sites') +
  geom_smooth(method=lm, se=TRUE, level=0.95))

FR_Chl_lm <- lm(data = Filter_data, L_hr_m2 ~ Chl_ug_L_Up)
summary(FR_Chl_lm)
par(mfrow=c(2,2))
plot(FR_Chl_lm)
```

```{r echo=FALSE}
# Turbidity
(FR_Turbidity <- ggplot(Filter_data, aes(Turbidity_NTU_Up, L_hr_m2, color = Site)) +
  geom_point() +
  theme_classic() +
  labs(x = 'Turbidity Upstream (NTU)',
       y = 'Clearence Rate (L/hr/m^2)',
       title = 'Filtration predicted by Turbidity - All Sites')) 
  
(FR_Turbidity_bestfit <- ggplot(Filter_data, aes(Turbidity_NTU_Up, L_hr_m2)) +
  geom_point() +
  theme_classic() +
  labs(x = 'Tubidity Upstream (NTU)',
       y = 'Clearence Rate (L/hr/m^2)',
       title = 'Filtration predicted by Turbidity - All Sites') +
  geom_smooth(method=lm, se=TRUE, level=0.95))

FR_Turb_lm <- lm(data = Filter_data, L_hr_m2 ~ Turbidity_NTU_Up)
summary(FR_Turb_lm)
par(mfrow=c(2,2))
plot(FR_Turb_lm)
```

TPM vs OC
```{r TPM vs OC, echo=FALSE}
TPM_OC_base <- ggplot(data = Avg_TPM_summary_table, aes(x = Avg_TPM, y = Avg_OC_Ratio, color = Site, label = Date))

TPM_OC_base + geom_point(size=4) + 
  labs(x = "Total Particulate Matter", y = "Average Organic Content Ratio", title = "TPM --> OC") + 
  theme_classic() +
  geom_text(aes(label=Date), nudge_x = 0.007, nudge_y = 0, check_overlap = T)

# Exclude low deanza value
exclude_low_deanza <- ggplot(data = (Avg_TPM_summary_table %>% filter(!(Site == "Deanza") | !(Date == "4/18/19"))), aes(x = Avg_TPM, y = Avg_OC_Ratio, color = Site, label = Date))

exclude_low_deanza + geom_point(size=4) + 
  labs(x = "Total Particulate Matter", y = "Average Organic Content Ratio", title = "TPM --> OC", subtitle = "Excluding NPD 4/18/19") + 
  theme_classic() +
  geom_text(aes(label=Date), nudge_x = 0.007, nudge_y = 0, check_overlap = T)
```
Plot individual Sites TPM vs OC
```{r TPM vs OC - By Site, echo=FALSE}
Avg_TPM_summary_table %>% 
  ggplot(aes(x = Avg_TPM, y = Avg_OC_Ratio, group = Site, color = Site)) +
  geom_point() +
  theme_classic() +
  labs(x = "Total Particulate Matter",
       y = 'Average Organic Content Ratio',
       title = 'OC predicted by TPM') +
  facet_wrap(~ Site) 

############ Deanza #############
Deanza_only <- ggplot(data = (Avg_TPM_summary_table %>% filter(Site == "Deanza")), aes(x = Avg_TPM, y = Avg_OC_Ratio, label = Date))

Deanza_only + geom_point(size=4, color = '#F8766D') + 
  labs(x = "Total Particulate Matter", y = "Average Organic Content Ratio", title = "TPM --> OC Deanza") + 
  theme_classic() +
  geom_text(aes(label=Date), nudge_x = 0.0003, nudge_y = 0, check_overlap = T)

############ Shellmaker ##########
Shellmaker_only <- ggplot(data = (Avg_TPM_summary_table %>% filter(Site == "Shellmaker")), aes(x = Avg_TPM, y = Avg_OC_Ratio, label = Date))

Shellmaker_only + geom_point(size=4, color = '#C77CFF') + 
  labs(x = "Total Particulate Matter", y = "Average Organic Content Ratio", title = "TPM --> OC Shellmaker") + 
  theme_classic() +
  geom_text(aes(label=Date), nudge_x = 0.0002, nudge_y = 0, check_overlap = T)

############ San Rafael ##########
SR_only <- ggplot(data = (Avg_TPM_summary_table %>% filter(Site == "San Rafael")), aes(x = Avg_TPM, y = Avg_OC_Ratio, label = Date))

SR_only + geom_point(size=4, color = '#00BFC4') + 
  labs(x = "Total Particulate Matter", y = "Average Organic Content Ratio", title = "TPM --> OC San Rafael") + 
  theme_classic() +
  geom_text(aes(label=Date), nudge_x = 0.005, nudge_y = 0, check_overlap = T)

############ Morro Bay ##########
MB_only <- ggplot(data = (Avg_TPM_summary_table %>% filter(Site == "Morro Bay")), aes(x = Avg_TPM, y = Avg_OC_Ratio, label = Date))

MB_only + geom_point(size=4, color = '#7CAE00') + 
  labs(x = "Total Particulate Matter", y = "Average Organic Content Ratio", title = "TPM --> OC Morro Bay") + 
  theme_classic() +
  geom_text(aes(label=Date), nudge_x = 0.0005, nudge_y = 0, check_overlap = T)
```


Olympia DTW predicted by Shell Length - Newport, CA
```{r Oly DTW - Shell length analysis, echo=FALSE}
NPD_oly <- NPD_density %>% 
  filter(species == "O. lurida") %>% 
  drop_na() %>% 
  as_tibble() %>%
  select(species, length_mm, tissue_dry_weight_g)

(Oly_shell_DTW <- ggplot(NPD_oly, aes(length_mm, tissue_dry_weight_g)) +
  geom_point() +
  theme_classic() +
  labs(x = 'Shell Length (mm)',
       y = 'Dry Tissue Weight (g)',
       title = 'Olympia Oyster DTW predicted by Shell Length - Newport, CA',
       subtitle = 'With outlier (bad data)') +
  geom_smooth(method=lm, se=TRUE, level=0.95))

Oly_DTW_lm <- lm(data = NPD_oly, tissue_dry_weight_g ~ length_mm)
summary(Oly_DTW_lm)
par(mfrow=c(2,2))
plot(Oly_DTW_lm)

# Outlier analysis (mean -+ SD * 2.2)
find_outlier <- function(data){
  average <- mean(data)
  stdev <- sd(data)
  outlier <- ifelse((data < (average - 2.2 * stdev) | (data > (average + 2.2 * stdev))),
         TRUE, FALSE)
}
# Remove outlier from graph 
NPD_oly_outlier <- NPD_oly %>% 
  mutate(DTW_outlier = find_outlier(NPD_oly$tissue_dry_weight_g))

(Oly_shell_DTW_rm_out <- ggplot(NPD_oly_outlier %>% 
                                  filter(DTW_outlier == FALSE), 
                                aes(length_mm, tissue_dry_weight_g)) +
  geom_point() +
  theme_classic() +
  labs(x = 'Shell Length (mm)',
       y = 'Dry Tissue Weight (g)',
       title = 'Olympia Oyster DTW predicted by Shell Length - Newport, CA',
       subtitle = 'Removed outlier') +
  geom_smooth(method=lm, se=TRUE, level=0.95))

# Linear model without outlier
Oly_DTZW_lm_rm_out <- lm(data = NPD_oly_outlier %>% 
                           filter(DTW_outlier == FALSE),
                         tissue_dry_weight_g ~ length_mm)

summary(Oly_DTZW_lm_rm_out)
par(mfrow=c(2,2))
plot(Oly_DTZW_lm_rm_out)
```

```{r eval=FALSE, include=FALSE}
## Test sbs correction - SBS corrections applied correctly
NPD_41519_Filter_plot <- fread(file.path("./output/2_Manual_Corrections_Applied", "Insitu_Filter_NPD_41519.csv"))
NPD_41519_Filter_plot <- NPD_41519_Filter_plot %>% 
  filter(Experiment == 'Filtration') 

(regular <- ggplot(NPD_41519_Filter_plot, aes(Time, Chl_ug_L, group = Position, color = Position)) + 
  geom_point())

NPD_41519_Filter_plot_sbs <- fread(file.path("./output/3_Sbs_Corrections_Applied", "Insitu_Filter_NPD_41519.csv"))
NPD_41519_Filter_plot_sbs <- NPD_41519_Filter_plot_sbs %>% 
  filter(Experiment == 'Filtration')

(adjusted <- ggplot(NPD_41519_Filter_plot_sbs, aes(Time, Chl_ug_L, group = Position, color = Position)) + 
  geom_point())

```

```{r}
#### Paired t-test all filtration trials --- Mean Upstream Chl vs Mean Downstream Chl

Master_analysis_table_FILTER <- Master_analysis_table %>%
  filter(Experiment == 'Filtration')

t.test(Master_analysis_table_FILTER$Chl_ug_L_Up,
       Master_analysis_table_FILTER$Chl_ug_L_Down,
       paired = TRUE,
       conf.level = 0.95)
## No difference between upstream and downstream Chl across all Filtraiton trails

##### Paired t-test on Positive L/hr/m^2 Filtration trails
Master_analysis_table_posFILTER <- Master_analysis_table %>% 
  filter(Experiment == 'Filtration',
         L_hr_m2 > 0)

t.test(Master_analysis_table_posFILTER$Chl_ug_L_Up,
       Master_analysis_table_posFILTER$Chl_ug_L_Down,
       paired = TRUE,
       conf.level = 0.95)
# No difference between upstream and downstream Chl across positive Filtration trials

######### Paired t-test on all trials (Filtraiton & Neg Control)
t.test(Master_analysis_table$Chl_ug_L_Up,
       Master_analysis_table$Chl_ug_L_Down,
       paried = TRUE,
       conf.level = 0.95)
## No difference between upstream and downstream Chl

Bar_up_down_data <- Master_analysis_table %>%
  select(Experiment, Date, Site, Chl_ug_L_Up, Chl_ug_L_Down) %>%
  rename(Upstream = Chl_ug_L_Up, Downstream = Chl_ug_L_Down) %>%  
  gather(Upstream, Downstream, key = Position, value = Chl_ug_L) %>% 
  mutate(Position = fct_relevel(Position, 'Upstream', 'Downstream')) %>% 
  mutate(Site = fct_relevel(Site, 'Deanza', 'Shellmaker', 'San Rafael', 'Morro Bay')) %>% 
  mutate(x_labels = ifelse(Experiment == 'Filtration',
                           Date,
                           paste(Date, '*', sep = ' '))) %>%
  mutate(Site_exp_date = paste(Site, Experiment,
                                     Date,
                                     sep = ' ')) %>% 
  mutate(Exp_Date = paste(Experiment, Date, sep = ' '))

#Bar_up_down_data$Position <- as.factor(Bar_up_down_data$Position)

(Paired_bar_chl_graph <- ggplot(data = Bar_up_down_data, aes(x = Site_exp_date, y = Chl_ug_L, fill = Position)) +
    geom_bar(stat="identity", position = "dodge") +
    theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) +
    facet_grid(~ Site, scales = "free", space = "free") + #'free' allows axis b/w sites uneaven
    geom_bar(data = (Bar_up_down_data %>%
                       filter(!Experiment %in% c('Filtration'))),
             color = "grey22",
             stat="identity",
             position = "dodge") +
    labs(x = 'Experiment', y = 'Chlorophyl (ug/L)'))
############## Try 2 ####### make separate graphs, combine using grid.arrange()
NPD_bar_data <- Bar_up_down_data %>% 
  filter(Site == 'Deanza')

(NPD_bar_graph <- ggplot(data = NPD_bar_data, aes(x = Exp_Date, y = Chl_ug_L, fill = Position)) +
    geom_col(position = position_dodge2(width = 0.9, preserve = "single")) +
    geom_col(data = (NPD_bar_data %>% # add boarder around Neg Control experiments
                       filter(!Experiment %in% c('Filtration'))),
             color = "black",
             position = "dodge") +
    theme_classic() +
    theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1),
          axis.title.x = element_blank(),
          legend.position = c(0.9, 0.8),
          plot.title = element_text(hjust = 0.5)) + # center title
    labs(y = 'Chlorophyll a (ug/L)', title = "Newport Deanza") +
    scale_x_discrete(labels = NPD_bar_data$Date) +
    ylim(0, 8))

NPSM_bar_data <- Bar_up_down_data %>% 
  filter(Site == 'Shellmaker')

(NPSM_bar_graph <- ggplot(data = NPSM_bar_data,
                          aes(x = Exp_Date, y = Chl_ug_L, fill = Position)) +
    geom_col(position = position_dodge2(width = 0.9, preserve = "single")) +
    geom_col(data = (NPSM_bar_data %>% # add boarder around Neg Control experiments
                       filter(!Experiment %in% c('Filtration'))),
             color = "black",
             position = "dodge") +
    theme_classic() +
    theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1),
          axis.title.y = element_blank(),
          axis.title.x = element_blank(),
          plot.title = element_text(hjust = 0.5)) + # center title
    labs(title = "Newport Shellmaker") +
    scale_x_discrete(labels = NPSM_bar_data$x_labels) +
    ylim(0, 8) +
    guides(fill = FALSE)) 

MB_bar_data <- Bar_up_down_data %>% 
  filter(Site == 'Morro Bay')

(MB_bar_graph <- ggplot(data = MB_bar_data,
                          aes(x = Exp_Date, y = Chl_ug_L, fill = Position)) +
    geom_col(position = position_dodge2(width = 0.9, preserve = "single")) +
    geom_col(data = (MB_bar_data %>% # add boarder around Neg Control experiments
                       filter(!Experiment %in% c('Filtration'))),
             color = "black",
             position = "dodge") +
    theme_classic() +
    theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1),
          axis.title.y = element_blank(),
          axis.title.x = element_blank(),
          plot.title = element_text(hjust = 0.5)) + # center title
    labs(title = "Morro Bay") +
    scale_x_discrete(labels = MB_bar_data$x_labels) +
    ylim(0, 8) +
    guides(fill = FALSE))

SR_bar_data <- Bar_up_down_data %>% 
  filter(Site == 'San Rafael')

(SR_bar_graph <- ggplot(data = SR_bar_data,
                          aes(x = Exp_Date, y = Chl_ug_L, fill = Position)) +
    geom_col(position = position_dodge2(width = 0.9, preserve = "single")) +
    geom_col(data = (SR_bar_data %>% # add boarder around Neg Control experiments
                       filter(!Experiment %in% c('Filtration'))),
             color = "black",
             position = "dodge") +
    theme_classic() +
    theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1),
          axis.title.y = element_blank(),
          axis.title.x = element_blank(),
          plot.title = element_text(hjust = 0.5)) + # center title
    labs(title = "San Rafael") +
    scale_x_discrete(labels = SR_bar_data$x_labels) +
    ylim(0, 8) +
    guides(fill = FALSE))

Chl_graphs <- list(NPD_bar_graph, NPSM_bar_graph, SR_bar_graph, MB_bar_graph) 
(grid.arrange(grobs = Chl_graphs,
             widths = c(1,1,1,1,1,1,1,1,1,1,1,1,1,1),
             layout_matrix = rbind(c(NA,1,1,1,1,1,1,1,1,1,1,1,1, NA),
                                   c(2,2,2,2,2,3,3,3,3,3,4,4,4,4))))
```